version: "3.3"

networks:
  celestia:
    ipam:
      driver: default
      config:
        - subnet: 172.27.10.0/24

services:
  full:
      container_name: full
      image: "sysrex/bridge1"
      ports:
        - "2121:2121"
        - "6000:6000"
        - "26658:26658"
      environment:
        - NODE_TYPE=full
        - CELESTIA_CUSTOM=arabica:C364B5937805342009408F7D44DBBF43C02AE227F968CF14C5001613B18CE419:/ip4/34.77.147.236/tcp/2121/p2p/12D3KooWNpRWxpi1APzV6CnwHvdgNRuTUbMNvg4ta2i1fnqYXR7H
      command: [
              "celestia", "full",
              "--node.store", "/root/.celestia-full",
              "start",
              "--headers.trusted-hash",
              "C364B5937805342009408F7D44DBBF43C02AE227F968CF14C5001613B18CE419"
               ]
      volumes:
        - /opt/validator3/data/full:/root:rw
      networks:
        celestia:
          ipv4_address: 172.27.10.12